---
:concurrency: <%= ENV.fetch("SIDEKIQ_CONCURRENCY") { 5 }.to_i %>
:pidfile: tmp/sidekiq.pid
:queues:
  - [asset_calculate, 1]
  - [order_after_create_all, 1]
  - [order_create, 1]
  - [session_expire, 1]
  - [session_log_create, 1]
  - [session_update, 1]
  - [sheet_parse, 1]
:limits:
  asset_calculate: 1
  order_after_create_all: 1
  order_create: 1
  session_expire: 1
  session_log_create: 1
  session_update: 1
  sheet_parse: 1

