---
:concurrency: 5
:logfile:     log/sidekiq.log
:pidfile:     tmp/pids/sidekiq.pid
production:
  :concurrency: 25
:queues:
  - default
  - database_changes
  - calculating
:limits:
  database_changes: 3
  calculating: 1
